### קביעת זמן משלוח עבור כל יום
POST http://localhost:3001/api/daily/schudleDelivery/640b57fd693e3147323f5ab1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA
Content-Type: application/json

{
    "date": "2023-09-03T12:00:00Z"
}

### כפתור קבלת הנחה על הזמנה
POST http://localhost:3001/api/daily/getDisFullOrder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### ירידת כמות מוצר בסל הקניות השבועי
POST http://localhost:3001/api/daily/decQuan/640b57fd693e3147323f5ab1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### תוספת כמות מוצר בסל הקניות השבועי
POST http://localhost:3001/api/daily/incQuan/640b57fd693e3147323f5ab1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### שינוי ימים של מוצר כלשהוא בסל הקניות השבועי
POST http://localhost:3001/api/daily/EditDays/640b57fd693e3147323f5ab1/Monday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### הסרת מוצר מסל הקניות השבועי
DELETE http://localhost:3001/api/daily/removeProduct/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### הוספת מוצר לסל הקניות השבועי
POST http://localhost:3001/api/daily/addProduct/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA
Content-Type: application/json

### פתיחת הזמנה
POST http://localhost:3001/api/daily/createOrder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA

### מחיקת כל המסמכים
DELETE http://localhost:3001/api/daily/deleteAll
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU1MDAxMywiZXhwIjoxNjgxMTQyMDEzfQ.KDoE5DOI05YtrX_91ZfHj73NeS_eZj_No--tl58jJnA
