### הוספת פריט לקייטרינגים
POST http://localhost:3001/api/manager/product/createProduct
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzEyMzE4MSwiZXhwIjoxNjc5NzE1MTgxfQ.kgJLK6BTd2xrSTC17enKG2v4W1eMxeH8y1M_v7kESX8

{
    "title":"סלט ירקות",
    "description":"סלט עם עגבנייה, מלפפון ובצל",
    "category":"salads",
    "price":5
}

### עדכון/עריכת פריט
POST http://localhost:3001/api/manager/product/editProduct/63f7a6a4e06a0b2e7d9601a0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzEyMzE4MSwiZXhwIjoxNjc5NzE1MTgxfQ.kgJLK6BTd2xrSTC17enKG2v4W1eMxeH8y1M_v7kESX8

{
    "title":"דשגשדגשדגשדגשדגשדשדשדגשדגש"
}

### מחיקת פריט
DELETE http://localhost:3001/api/manager/product/deleteProduct/63f7a6f9e06a0b2e7d9601ab
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzEyMzE4MSwiZXhwIjoxNjc5NzE1MTgxfQ.kgJLK6BTd2xrSTC17enKG2v4W1eMxeH8y1M_v7kESX8

### מחיקת כל הפריטים
DELETE http://localhost:3001/api/manager/product/deleteAll/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjY1MzNjODE4NGVkYWMwNTdiMjNkYiIsImlhdCI6MTY3NzA4NzU5NCwiZXhwIjoxNjc5Njc5NTk0fQ.NaVZR9wOxOhC_dsGQNNkRaTvhEHfaAYzP2YaVqLqynE


###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"matan", 
    "email":"inviteserv@gmail.com",
    "password":"123123ssSS@@",
}

###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"inviteserv@gmail.com",
    "password":"123123"
}

###GET All Users :
GET http://localhost:3001/api/auth/



