### ---- הסרת מוצר מיום מסויים ----
PUT http://localhost:3001/api/days/removeProduct/63f970d02972e5d94952d761/Sunday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3ODI4MjYzOSwiZXhwIjoxNjgwODc0NjM5fQ.XudcJAK1jhj1Zqbs6HxCD9DSaJT9VLLXE3wkIaaPhzk

### ---- הוספת מוצר ליום מסויים ----
PUT http://localhost:3001/api/days/addProduct/63f970d02972e5d94952d761/Wednesday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3ODI4MjYzOSwiZXhwIjoxNjgwODc0NjM5fQ.XudcJAK1jhj1Zqbs6HxCD9DSaJT9VLLXE3wkIaaPhzk

### הוספת פריט לקייטרינגים
POST http://localhost:3001/api/manager/product/createProduct
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3ODI4MjYzOSwiZXhwIjoxNjgwODc0NjM5fQ.XudcJAK1jhj1Zqbs6HxCD9DSaJT9VLLXE3wkIaaPhzk

{
    "title":"סלט ירקות",
    "description":"סלט עם עגבנייה, מלפפון ובצל",
    "category":"salads",
    "price":5
}

### עדכון/עריכת פריט
POST http://localhost:3001/api/manager/product/editProduct/63f7a6a4e06a0b2e7d9601a0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3ODI4MjYzOSwiZXhwIjoxNjgwODc0NjM5fQ.XudcJAK1jhj1Zqbs6HxCD9DSaJT9VLLXE3wkIaaPhzk

{
    "title":"דשגשדגשדגשדגשדגשדשדשדגשדגש"
}

### מחיקת פריט
DELETE http://localhost:3001/api/manager/product/deleteProduct/63f7a6f9e06a0b2e7d9601ab
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3ODI4MjYzOSwiZXhwIjoxNjgwODc0NjM5fQ.XudcJAK1jhj1Zqbs6HxCD9DSaJT9VLLXE3wkIaaPhzk

### מחיקת כל הפריטים
DELETE http://localhost:3001/api/manager/product/deleteAll/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjY1MzNjODE4NGVkYWMwNTdiMjNkYiIsImlhdCI6MTY3NzA4NzU5NCwiZXhwIjoxNjc5Njc5NTk0fQ.NaVZR9wOxOhC_dsGQNNkRaTvhEHfaAYzP2YaVqLqynE


###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"matan", 
    "email":"inviteserv@gmail.com",
    "password":"123123123",
}

###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"inviteserv@gmail.com",
    "password":"123123"
}

###GET All Users :
GET http://localhost:3001/api/auth/



