
### POST Random score push test :
POST http://localhost:3001/api/moderator/gather/pushRandomScoreTest/63e963a9af9a14425b95551f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWU0YzcyZDBmZGUyODdiNDE0YmM1ZSIsImlhdCI6MTY3NjYxOTE2NywiZXhwIjoxNjc5MjExMTY3fQ.K-_S74sarVuZyouo27fex0BGyjQZDwk0_kv2j5fJKm4

[
{"userId": "63ef39317bc23715b3e4d957",
"kill": "20","death":"10","assist": "5"},
{"userId": "63ef393f7bc23715b3e4d95c",
"kill": "20","death":"10","assist": "5"}
]

### POST score push :
POST http://localhost:3001/api/admin/gather/insertScore/63ee2ad573a9bb747a2ab292
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWU0YzcyZDBmZGUyODdiNDE0YmM1ZSIsImlhdCI6MTY3NjYxOTE2NywiZXhwIjoxNjc5MjExMTY3fQ.K-_S74sarVuZyouo27fex0BGyjQZDwk0_kv2j5fJKm4


{"userId": "63ef55dfe9e65c3302ca7128",
"kill": 20,"death":10,"assist": 5}


###DELETE ALL Users :
DELETE http://localhost:3001/api/auth/deleteAll


###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"Bulbul", 
    "email":"ine232122513rv@gmail.com",
    "password":"123123ssSS@@",
    "score": {
        "kill":0,
        "death":0,
        "assist":0,
        "points":0
    }
}


###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"invidts2erv@gmail.com",
    "password":"123123ssSS@@"
}

###GET All Users :
GET http://localhost:3001/api/auth/


###GET ALL Gather :
GET http://localhost:3001/api/gather


###GET Single Gather :
GET http://localhost:3001/api/gather/63eb140ce87ee161d0805323


### POST Add to Gather :
## host/api/gather/add/gatherId
POST http://localhost:3001/api/gather/add/63ea2578c2af8bd9e9913907
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI5MjQ0NSwiZXhwIjoxNjc4ODg0NDQ1fQ.QApYG_NK22GRLjWAwh8Vq0KUMWz4-X3Wpyw7VRAs_aA

### POST Leave the Gather :
## host/api/gather/leaveQueue/userId
DELETE http://localhost:3001/api/gather/leaveQueue/63ea2578c2af8bd9e9913907
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI5MjQ0NSwiZXhwIjoxNjc4ODg0NDQ1fQ.QApYG_NK22GRLjWAwh8Vq0KUMWz4-X3Wpyw7VRAs_aA

###POST when gather is started:
POST http://localhost:3001/api/gather/startGather/63ec2012c8eb5ac8fc6b1d4f

###
GET http://localhost:3001/api/books/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTI0ZThiY2M4MmU5YjRiOWQ4ODhhOSIsImlhdCI6MTY3NTc3NTcyOCwiZXhwIjoxNjc4MzY3NzI4fQ.QLMLLY1_upVsULKO6FYnVCnHWqlNElKzPfxtU88j5x0
###
GET http://localhost:3001/api/books/fantasy
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTI0ZThiY2M4MmU5YjRiOWQ4ODhhOSIsImlhdCI6MTY3NTc3NTcyOCwiZXhwIjoxNjc4MzY3NzI4fQ.QLMLLY1_upVsULKO6FYnVCnHWqlNElKzPfxtU88j5x0

###
GET http://localhost:3001/api/books/mod
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTcxMDI5NDZiNjk0MDEyM2U4YTIzZSIsImlhdCI6MTY3NjExNDg5MSwiZXhwIjoxNjc4NzA2ODkxfQ.hoA67CRrhb08fe-5LdxzNGSMwE_teCPA1SiDyR4pgjU


### POST to add a card:
POST http://localhost:3001/api/cards
Content-Type: application/json

{
    "name": "Pizza Dominos",
    "description": "Best Pizza in some place",
    "address": "some place",
    "phone": "050-5050022",
    "image":"http://abc.com/image.png",
    "bizNumber":1233123123
}

### GET all cards
GET http://localhost:3001/api/cards


### GET all students:
GET http://localhost:3001/api/students

###POST to add a student:
POST http://localhost:3001/api/students
Content-Type: application/json

{
    "firstName":"Bruce", 
    "lastName":"Wayne",
    "email":"Batman@Batcave.com"
}




###POST to Create Gather :
POST http://localhost:3001/api/admin/gather/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWYzOTNmN2JjMjM3MTViM2U0ZDk1YyIsImlhdCI6MTY3NjY2ODEzOCwiZXhwIjoxNjc5MjYwMTM4fQ.0Cxe--XPfxrwCHXJ6KFY508V9n-4GGp6mSb60jzfRvI

{
    "map":"Ascent",
    "maxPlayers":"10",
    "date":"21-05-1995"
}


###DELETE ALL Gather :
DELETE http://localhost:3001/api/moderator/gather/deleteAll
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWRhYjkwMzllMTE1Nzk3OTBlNjU4YSIsImlhdCI6MTY3NjUyMTE1NCwiZXhwIjoxNjc5MTEzMTU0fQ.VQO7kAn7xvVaZzXT8a_2w26mblbWWFVs-3RpybCphqc

###DELETE Single Gather :
DELETE http://localhost:3001/api/gather/delete/63e94c5d47196f2273f5de07


### POST Edit Gather :
POST http://localhost:3001/api/gather/edit/63e9f07caa5eaa0e76ef863f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI3NTgxNywiZXhwIjoxNjc4ODY3ODE3fQ.W0Gc1co9uEFMclmyCauLZGWkcLyQSYFAGnD83VfFcx0

{
"map":"Icebox",
"maxPlayers": 8,
"status":false,
"players": []
}



###POST to Add Role :
POST http://localhost:3001/api/role/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTk2YWJkNjczMDk4M2NlNTQ4YTA0ZiIsImlhdCI6MTY3NjI0MTYzNSwiZXhwIjoxNjc4ODMzNjM1fQ.kLGlAPt4B6FJl_7VNT3yneDEvUxT5fvAr-WLS_ORSZw

{
    "username":"matan",
    "role":"moderator"
}


###POST Admin to DELETE Player from Queue :
## host/api/player/delete/gatherid/userid
POST http://localhost:3001/api/player/delete/63ea2578c2af8bd9e9913907/63e9d4d83bc24fc5d36ed50a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI4ODI2OSwiZXhwIjoxNjc4ODgwMjY5fQ.dsIBdlYWn-CZB7R7i7RuVJ_aoMpDMbN3SwLau0hGCTo



### POST Push test players for testing :
## host/api/gather/pushTestPlayers/gatherId
POST http://localhost:3001/api/moderator/gather/pushTestPlayers/63f4398901decc936590ee3f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWYzOTNmN2JjMjM3MTViM2U0ZDk1YyIsImlhdCI6MTY3NjY2ODEzOCwiZXhwIjoxNjc5MjYwMTM4fQ.0Cxe--XPfxrwCHXJ6KFY508V9n-4GGp6mSb60jzfRvI

{
 "body":
[
   {"userId": "63efed3063ea52753fbea819","userName":"Homo"},
   {"userId": "63efed4963ea52753fbea81e","userName":"Bulbul2"},
   {"userId": "63efed5463ea52753fbea823","userName":"Caravaliho"},
   {"userId": "63efed5d63ea52753fbea828","userName":"Benzema"},
   {"userId": "63efed6a63ea52753fbea82d","userName":"Hole Nefesh"},
   {"userId": "63efed7663ea52753fbea832","userName":"Bang0"},
   {"userId": "63efed8363ea52753fbea837","userName":"Jacky Chan"},
   {"userId": "63efed8f63ea52753fbea83c","userName":"Ronaldo"},
   {"userId": "63efed9763ea52753fbea842","userName":"Mpabe"},
   {"userId": "63efeda263ea52753fbea847","userName":"Bulbul"}
   ]
}


