### GET All Cart Products
GET http://localhost:3001/api/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### is Product In Cart?
GET http://localhost:3001/api/is/isProductInCart/63f91c2102bb15f055bf13f2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### GET All Categories
GET http://localhost:3001/api/category

### Create an order package from cart
POST http://localhost:3001/api/cart/createOrderPackage
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### decrement Quantity in cart
POST http://localhost:3001/api/cart/decQuantity/63f7c094af9209d27ec7ad28
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### increment Quantity in cart
POST http://localhost:3001/api/cart/incQuantity/63f7c094af9209d27ec7ad28
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### uploadCart 
POST http://localhost:3001/api/cart/uploadCart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### Add To Cart--->
POST http://localhost:3001/api/cart/addToCart/63f7c094af9209d27ec7ad28
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

### Remove From Cart--->
DELETE http://localhost:3001/api/cart/deleteFromCart/63f7c094af9209d27ec7ad28
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3NzMzNzAwOSwiZXhwIjoxNjc5OTI5MDA5fQ.uWd3CRcZgb5mCGQUB-qoSV6a2Fs1IxRukVptePJaIYk

###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"matan", 
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}

###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}

###GET All Users :
GET http://localhost:3001/api/auth/


### קנייה של פריטים מסל הקניות



