### GET Products from some Date
GET http://localhost:3001/api/days/Sunday

### Edit Password - USERS -------
POST http://localhost:3001/api/auth/editPassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0
Content-Type: application/json

{
 "password": "saddkalskl22"   
}

### Edit Email - USERS -------
POST http://localhost:3001/api/auth/editEmail
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0
Content-Type: application/json

{
 "email": "inviteserv2@gmail.com"   
}

### Add worker to some cartItem
DELETE http://localhost:3001/api/cart/deleteWorkerPermanently/431b2c90-1dc2-44e4-ae6f-4cf34c2fe5e6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### Add worker to some cartItem
POST http://localhost:3001/api/cart/signWorker/f7c1b058-bcb9-4262-9816-75ab7d20de95/63fe1b05f0847e5b32120846
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### Get Self User -->
GET http://localhost:3001/api/auth/getSelfUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### Add Worker To user -->
POST http://localhost:3001/api/cart/addWorker
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0
Content-Type: application/json

{
"name":"sadasdasdasddas"
}

### GET Single Order
GET http://localhost:3001/api/order/63fd017f53dbc33ac452a8c4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### GET All Orders
GET http://localhost:3001/api/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### GET Single Cart Product
GET http://localhost:3001/api/cart/63f970d02972e5d94952d761
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### GET All Cart Products
GET http://localhost:3001/api/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### is Product In Cart?
GET http://localhost:3001/api/is/isProductInCart/63f91c2102bb15f055bf13f2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### GET All Categories
GET http://localhost:3001/api/category

### Create an order package from cart
POST http://localhost:3001/api/cart/createOrderPackage
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### decrement Quantity in cart
POST http://localhost:3001/api/cart/decQuantity/63f970d02972e5d94952d761
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### increment Quantity in cart
POST http://localhost:3001/api/cart/incQuantity/63f970d02972e5d94952d761
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### uploadCart 
POST http://localhost:3001/api/cart/uploadCart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### Add To Cart--->
POST http://localhost:3001/api/cart/addToCart/63f970d02972e5d94952d761
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

### Remove From Cart--->
DELETE http://localhost:3001/api/cart/deleteFromCart/63f970d02972e5d94952d761
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkZTRiNTc2Y2QxNzhmYWI1MDhjZSIsImlhdCI6MTY3Nzg5NjEyMSwiZXhwIjoxNjgwNDg4MTIxfQ.gv0Vx-q46g6NrpVWL1F-3_bYKbFAFJn2GRvxmRSI_A0

###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"matan", 
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}

###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}

###GET All Users :
GET http://localhost:3001/api/auth/


### קנייה של פריטים מסל הקניות



