### Checkout Cart
POST http://localhost:3001/api/product/checkout/uyDR1RDyR
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjY1MzNjODE4NGVkYWMwNTdiMjNkYiIsImlhdCI6MTY3NzA4NzU5NCwiZXhwIjoxNjc5Njc5NTk0fQ.NaVZR9wOxOhC_dsGQNNkRaTvhEHfaAYzP2YaVqLqynE


### Add To Cart--->
POST http://localhost:3001/api/product/addToCart/63f6d90a8a8a52b838abb530
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjZkOGM3OGE4YTUyYjgzOGFiYjUyNiIsImlhdCI6MTY3NzEyMTg5NCwiZXhwIjoxNjc5NzEzODk0fQ.u9hl4a6qbJumFOvC1lMNrqIfmIgqFzUODQhvu6Bye7Y

### Remove From Cart--->
DELETE http://localhost:3001/api/product/deleteFromCart/uyDR1RDyR
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjY1MzNjODE4NGVkYWMwNTdiMjNkYiIsImlhdCI6MTY3NzA4NzU5NCwiZXhwIjoxNjc5Njc5NTk0fQ.NaVZR9wOxOhC_dsGQNNkRaTvhEHfaAYzP2YaVqLqynE


###POST to add user:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"matan", 
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}


###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
    "email":"inviteserv@gmail.com",
    "password":"123123123"
}

###GET All Users :
GET http://localhost:3001/api/auth/


### קנייה של פריטים מסל הקניות



