
### קביעת זמן משלוח עבור כל יום
POST http://localhost:3001/api/weekly/schudleDelivery/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk
Content-Type: application/json

{
    "date": "2023-09-03T12:00:00Z"
}

### כפתור קבלת הנחה על הזמנה
POST http://localhost:3001/api/weekly/getDisFullOrder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### ירידת כמות מוצר בסל הקניות השבועי
POST http://localhost:3001/api/weekly/decQuan/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### תוספת כמות מוצר בסל הקניות השבועי
POST http://localhost:3001/api/weekly/incQuan/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### שינוי ימים של מוצר כלשהוא בסל הקניות השבועי
POST http://localhost:3001/api/weekly/EditDays/640b4a6b75463ff658e8eacf/Monday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### הסרת מוצר מסל הקניות השבועי
DELETE http://localhost:3001/api/weekly/removeProduct/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### הוספת מוצר לסל הקניות השבועי
POST http://localhost:3001/api/weekly/addProduct/640b4a6b75463ff658e8eacf
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk
Content-Type: application/json

{
"days":["Sunday"]
}

### פתיחת הזמנה
POST http://localhost:3001/api/weekly/createOrder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk

### מחיקת כל המסמכים
DELETE http://localhost:3001/api/weekly/deleteAll
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGM5NmUyMDlmOTg2OTkxM2VhM2IzOCIsImlhdCI6MTY3ODU0NzE5MiwiZXhwIjoxNjgxMTM5MTkyfQ.HUguQNGJZdNsqg1TWvcpY4ItX3OK-JrX7c4ymclLHKk
